OnlineLearningSystem/Pages/Accounts/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineLearningSystem.Models;

namespace OnlineLearningSystem.Pages.Accounts
{
    public class CreateModel : PageModel
    {
        private readonly OnlineLearningSystem.Models.OLS_DBContext _context;

        public CreateModel(OnlineLearningSystem.Models.OLS_DBContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Account Account { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Accounts == null || Account == null)
            {
                return Page();
            }

            _context.Accounts.Add(Account);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

OnlineLearningSystem/Pages/Accounts/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OnlineLearningSystem.Models;

namespace OnlineLearningSystem.Pages.Accounts
{
    public class DeleteModel : PageModel
    {
        private readonly OnlineLearningSystem.Models.OLS_DBContext _context;

        public DeleteModel(OnlineLearningSystem.Models.OLS_DBContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Account Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FirstOrDefaultAsync(m => m.AccountId == id);

            if (account == null)
            {
                return NotFound();
            }
            else 
            {
                Account = account;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return NotFound();
            }
            var account = await _context.Accounts.FindAsync(id);

            if (account != null)
            {
                Account = account;
                _context.Accounts.Remove(Account);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

OnlineLearningSystem/Pages/Accounts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OnlineLearningSystem.Models;

namespace OnlineLearningSystem.Pages.Accounts
{
    public class DetailsModel : PageModel
    {
        private readonly OnlineLearningSystem.Models.OLS_DBContext _context;

        public DetailsModel(OnlineLearningSystem.Models.OLS_DBContext context)
        {
            _context = context;
        }

      public Account Account { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FirstOrDefaultAsync(m => m.AccountId == id);
            if (account == null)
            {
                return NotFound();
            }
            else 
            {
                Account = account;
            }
            return Page();
        }
    }
}

OnlineLearningSystem/Pages/Accounts/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineLearningSystem.Models;

namespace OnlineLearningSystem.Pages.Accounts
{
    public class EditModel : PageModel
    {
        private readonly OnlineLearningSystem.Models.OLS_DBContext _context;

        public EditModel(OnlineLearningSystem.Models.OLS_DBContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Account Account { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return NotFound();
            }

            var account =  await _context.Accounts.FirstOrDefaultAsync(m => m.AccountId == id);
            if (account == null)
            {
                return NotFound();
            }
            Account = account;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Account).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AccountExists(Account.AccountId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AccountExists(int id)
        {
          return (_context.Accounts?.Any(e => e.AccountId == id)).GetValueOrDefault();
        }
    }
}

OnlineLearningSystem/Pages/ClassStudents/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineLearningSystem.Models;

namespace OnlineLearningSystem.Pages.ClassStudents
{
    public class CreateModel : PageModel
    {
        private readonly OnlineLearningSystem.Models.OLS_DBContext _context;

        public CreateModel(OnlineLearningSystem.Models.OLS_DBContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["ClassId"] = new SelectList(_context.Classrooms, "ClassId", "ClassId");
        ViewData["StudentId"] = new SelectList(_context.Accounts, "AccountId", "AccountId");
            return Page();
        }

        [BindProperty]
        public ClassStudent ClassStudent { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.ClassStudents == null || ClassStudent == null)
            {
                return Page();
            }

            _context.ClassStudents.Add(ClassStudent);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

OnlineLearningSystem/Pages/ClassStudents/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OnlineLearningSystem.Models;

namespace OnlineLearningSystem.Pages.ClassStudents
{
    public class DeleteModel : PageModel
    {
        private readonly OnlineLearningSystem.Models.OLS_DBContext _context;

        public DeleteModel(OnlineLearningSystem.Models.OLS_DBContext context)
        {
            _context = context;
        }

        [BindProperty]
      public ClassStudent ClassStudent { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.ClassStudents == null)
            {
                return NotFound();
            }

            var classstudent = await _context.ClassStudents.FirstOrDefaultAsync(m => m.ClassStudentId == id);

            if (classstudent == null)
            {
                return NotFound();
            }
            else 
            {
                ClassStudent = classstudent;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.ClassStudents == null)
            {
                return NotFound();
            }
            var classstudent = await _context.ClassStudents.FindAsync(id);

            if (classstudent != null)
            {
                ClassStudent = classstudent;
                _context.ClassStudents.Remove(ClassStudent);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

OnlineLearningSystem/Pages/ClassStudents/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OnlineLearningSystem.Models;

namespace OnlineLearningSystem.Pages.ClassStudents
{
    public class DetailsModel : PageModel
    {
        private readonly OnlineLearningSystem.Models.OLS_DBContext _context;

        public DetailsModel(OnlineLearningSystem.Models.OLS_DBContext context)
        {
            _context = context;
        }

      public ClassStudent ClassStudent { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.ClassStudents == null)
            {
                return NotFound();
            }

            var classstudent = await _context.ClassStudents.FirstOrDefaultAsync(m => m.ClassStudentId == id);
            if (classstudent == null)
            {
                return NotFound();
            }
            else 
            {
                ClassStudent = classstudent;
            }
            return Page();
        }
    }
}

OnlineLearningSystem/Pages/ClassStudents/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineLearningSystem.Models;

namespace OnlineLearningSystem.Pages.ClassStudents
{
    public class EditModel : PageModel
    {
        private readonly OnlineLearningSystem.Models.OLS_DBContext _context;

        public EditModel(OnlineLearningSystem.Models.OLS_DBContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ClassStudent ClassStudent { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.ClassStudents == null)
            {
                return NotFound();
            }

            var classstudent =  await _context.ClassStudents.FirstOrDefaultAsync(m => m.ClassStudentId == id);
            if (classstudent == null)
            {
                return NotFound();
            }
            ClassStudent = classstudent;
           ViewData["ClassId"] = new SelectList(_context.Classrooms, "ClassId", "ClassId");
           ViewData["StudentId"] = new SelectList(_context.Accounts, "AccountId", "AccountId");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ClassStudent).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ClassStudentExists(ClassStudent.ClassStudentId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ClassStudentExists(int id)
        {
          return (_context.ClassStudents?.Any(e => e.ClassStudentId == id)).GetValueOrDefault();
        }
    }
}

OnlineLearningSystem/Pages/GenerateAccount/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using OnlineLearningSystem.Models;
using OnlineLearningSystem.Pages.ClassSubjectTests;

namespace OnlineLearningSystem.Pages.GenerateAccount
{
    public class CreateModel : PageModel
    {
        private readonly OnlineLearningSystem.Models.OLS_DBContext _context;

        public CreateModel(OnlineLearningSystem.Models.OLS_DBContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Account Account { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Accounts == null || Account == null)
            {
                return Page();
            }

            _context.Accounts.Add(Account);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }




        //-----------------
        [BindProperty]
        public IFormFile ExcelFile { get; set; } = default!;
        [BindProperty]
        public string TestID { get; set; } = default!;
        public async Task<IActionResult> OnPostImportAccount()
        {
            if (ExcelFile == null || ExcelFile.Length == 0)
            {
                TempData["ToastMessage"] = "File Excel không được để trống!";
                return RedirectToPage("/GenerateAccount/Create");
            }

            // Read file excel here
            var accounts = await ReadExcelAsync(ExcelFile);
            foreach (var item in accounts)
            {
              
                _context.Accounts.Add(item);
                await _context.SaveChangesAsync();


               
                
            }
            TempData["ToastMessage"] = "Nhập câu hỏi từ file Excel thành công!";
            return RedirectToPage("/GenerateAccount/Index");
        }

        private async Task<List<Account>> ReadExcelAsync(IFormFile excelFile)
        {
            var accountList = new List<Account>();
            

            using (var stream = new MemoryStream())
            {
                await excelFile.CopyToAsync(stream);
                stream.Position = 0;

                IWorkbook workbook = new XSSFWorkbook(stream);
                ISheet sheet = workbook.GetSheetAt(0);

                for (int row = 1; row <= sheet.LastRowNum; row++)
                {
                    Account account = new Account();
                    IRow currentRow = sheet.GetRow(row);
                    if (currentRow != null)
                    {
                        
                        ICell fullNameCell = currentRow.GetCell(0);
                        ICell emailCell = currentRow.GetCell(1);

                        account.Fullname = fullNameCell.ToString();
                        account.Username = "test";
                        account.Email = emailCell.ToString();
                        account.Password = "abcd1234";
                        account.Role = "Student";
                        account.Status = true;
                        accountList.Add(account);
                   
                    }
                    
                }
            }

            return accountList;
        }

        private string GetCellValueAsString(ICell cell)
        {
            switch (cell.CellType)
            {
                case CellType.String:
                    return cell.StringCellValue;
                case CellType.Numeric:
                    return cell.NumericCellValue.ToString();
                case CellType.Boolean:
                    return cell.BooleanCellValue.ToString();
                case CellType.Formula:
                    return cell.CellFormula;
                default:
                    return string.Empty;
            }
        }
    }
}

OnlineLearningSystem/Pages/GenerateAccount/Create.cshtml
@page
@model OnlineLearningSystem.Pages.GenerateAccount.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create Account</h2>

<form method="post" enctype="multipart/form-data" asp-page-handler="ImportAccount">
    <div class="form-group">
        <label for="ExcelFile">Upload Excel File</label>
        <input type="file" name="ExcelFile" id="ExcelFile" class="form-control" />
        <span asp-validation-for="ExcelFile" class="text-danger"></span>
    </div>

  
    <button type="submit" class="btn btn-primary">Import</button>
</form>

@if (TempData["ToastMessage"] != null)
{
    <div class="alert alert-success mt-3">
        @TempData["ToastMessage"]
    </div>
}

OnlineLearningSystem/Pages/GenerateAccount/Delete.cshtml
@page
@model OnlineLearningSystem.Pages.GenerateAccount.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Username)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Username)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Password)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Password)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Fullname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Fullname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Role)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Role)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Status)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Account.AccountId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

OnlineLearningSystem/Pages/GenerateAccount/Details.cshtml
@page
@model OnlineLearningSystem.Pages.GenerateAccount.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Username)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Username)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Password)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Password)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Fullname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Fullname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Role)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Role)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Account?.AccountId">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

OnlineLearningSystem/Pages/GenerateAccount/Edit.cshtml
@page
@model OnlineLearningSystem.Pages.GenerateAccount.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Account</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Account.AccountId" />
            <div class="form-group">
                <label asp-for="Account.Username" class="control-label"></label>
                <input asp-for="Account.Username" class="form-control" />
                <span asp-validation-for="Account.Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Account.Password" class="control-label"></label>
                <input asp-for="Account.Password" class="form-control" />
                <span asp-validation-for="Account.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Account.Fullname" class="control-label"></label>
                <input asp-for="Account.Fullname" class="form-control" />
                <span asp-validation-for="Account.Fullname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Account.Email" class="control-label"></label>
                <input asp-for="Account.Email" class="form-control" />
                <span asp-validation-for="Account.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Account.Role" class="control-label"></label>
                <input asp-for="Account.Role" class="form-control" />
                <span asp-validation-for="Account.Role" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Account.Status" /> @Html.DisplayNameFor(model => model.Account.Status)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineLearningSystem/Pages/GenerateAccount/Index.cshtml
@page
@model OnlineLearningSystem.Pages.GenerateAccount.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Account[0].Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Account[0].Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Account[0].Fullname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Account[0].Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Account[0].Role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Account[0].Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Account) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fullname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.AccountId">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.AccountId">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.AccountId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>